### ISSUE TITLE
Documentation updates needed

### ISSUE THREAD

**Issue by fn87** [simshine-sdk/simcam#2]
1. Multiple curl examples does not work. 
2. Full walkthrough of how to use SDK are missing.

Currently, very few things are working as it should and I hope that it is due to me not having enough information and the lack of good documentation.

Examples, rotation gives 501 not implemented. Adding your own endpoints for events gives 400 using both example and my own code.

**Comment by simshine-sdk** [comment]
In the latest version, we have simplified the api call dependency, making these interfaces easier to use.Sincerely hope you can try it again, and we will continue to improve its functions
